### ISSUE TITLE
Unable to process !array

### ISSUE THREAD

**Issue by BrennanRoberts** [Oblong/plasma-js-bridge#17]
When attempting to parse proteins containing `!array`, the following error is displayed:

> Yaml error handling protein: {"name":"YAMLException","reason":"unknown tag !<tag:oblong.com,2009:slaw/array>","mark":{"name":null,"buffer":"# peek - g-speak 3.27.1 (RelWithDebInfo), libYaml 0.1.4\n%YAML 1.1\n%TAG ! tag:oblong.com,2009:slaw/\n--- !protein\ndescrips:\n- wandreader-topology\n- version.2\ningests:\n  origins:\n  - name: wandreader-1-pid3675x1\n    clock: 802953\n    systime: 1472747927.6328609\n  topology:\n    wands-per-radio: 2\n    radio-found-count: 2\n    channel-range: !array [1, 10]\n    radio-type: 900MHz\n\u0000","position":352,"line":15,"column":33},"message":"unknown tag !<tag:oblong.com,2009:slaw/array> at line 16, column 34:\n        channel-range: !array [1, 10]\n                                     ^"}

**Comment by tomjakubowski** [comment]
closed by #18
